defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: hackety_hack_com_development

test:
  <<: *defaults
  database: hackety_hack_com_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: <%= URI.parse(EY::Config.get(:mongolab, 'MONGOLAB_URI')) %>
  database: hackety_hack_com
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
